# Stage 1: Build the Angular application
FROM node:18.17.1-alpine AS build

# Setup the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
# For safer side
RUN npx ngcc -properties es2023 browser module main --first-only --create-ivy-entry-points

# Copy other files and folders to the working directory
COPY . .

# Build Angular application in PROD mode
RUN npm run build

# Stage 2: Serve the application using Nginx satble version.
FROM nginx:stable

# Copy built Angular app files to Nginx HTML folder
COPY --from=build /app/dist/msa-ui/ /usr/share/nginx/html

# Expose port 8080
EXPOSE 8080

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
